version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
            - ./public:/var/www/public
            # - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - redis
        networks:
            - panel_client

    dockerctl:
        container_name: dockerctl
        build:
            context: ./ctl
            dockerfile: Dockerfile
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
        - panel_client
        restart: unless-stopped
        ports:
          - "3000:3000"

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - panel_client

    # db mysql
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-panel_client}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - panel_client

    # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "8082:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
        networks:
            - panel_client

    # redis
    redis:
        image: redis:latest
        networks:
            - panel_client


networks:
    panel_client:
        driver: bridge